digit = { ASCII_DIGIT }
dot = { "."}
space = { " " | "\t" }
double_quote = { "\"" }
crlf = { NEWLINE }

//
// character
//

utf8_character =
{
  '\u{0020}'  .. '\u{007E}'  |
  '\u{00A0}'  .. '\u{D7FF}'  |
  '\u{F900}'  .. '\u{FDCF}'  |
  '\u{FDF0}'  .. '\u{FFEF}'  |
  '\u{10000}' .. '\u{1FFFD}' |
  '\u{20000}' .. '\u{2FFFD}' |
  '\u{30000}' .. '\u{3FFFD}' |
  '\u{40000}' .. '\u{4FFFD}' |
  '\u{50000}' .. '\u{5FFFD}' |
  '\u{60000}' .. '\u{6FFFD}' |
  '\u{70000}' .. '\u{7FFFD}' |
  '\u{80000}' .. '\u{8FFFD}' |
  '\u{90000}' .. '\u{9FFFD}' |
  '\u{A0000}' .. '\u{AFFFD}' |
  '\u{B0000}' .. '\u{BFFFD}' |
  '\u{C0000}' .. '\u{CFFFD}' |
  '\u{D0000}' .. '\u{DFFFD}' |
  '\u{E0000}' .. '\u{EFFFD}'
}
non_crlf_utf8_character = {
  !crlf ~ utf8_character
}

//
// padding
//

inline_padding = { space }
singleline_padding = { space }
multiline_padding = { space | crlf  }

//
// number
//

base_part = { ( digit+ ~ dot ~ digit* ) | ( dot? ~ digit+ )}
number = { "-"? ~ base_part }

//
// string
//

singleline_double_quote_contents =
{
  !double_quote ~ non_crlf_utf8_character
}
singleline_double_quote_string =
{
  double_quote ~ ( singleline_double_quote_contents )* ~ double_quote
}
double_quote_string = { singleline_double_quote_string }
string = { double_quote_string }

//
// identifier
//

base_identifier = { ( XID_START | "_" ) ~ XID_CONTINUE* }
cxx_namespaced_identifier = { base_identifier ~ ( "::" ~ base_identifier )* }
identifier = { cxx_namespaced_identifier }

//
// assignment
//

assignment = { ( space )* ~ "=" ~ ( space )* }

//
// metadata
//

atomic_value = { number  | identifier | string }
typed_value = { atomic_value }
metadata_value = { "None" | typed_value }
key_value_metadata = { identifier ~ assignment ~ metadata_value }
doc_metadata = { "doc" ~ assignment ~ string }
shared_metadata = { string | key_value_metadata | doc_metadata }

//
// header
//

statement_separator = { crlf | ";" }
layer_metadata_item = { shared_metadata }
layer_metadata_item_sequence = {
  layer_metadata_item ~
  ( ( singleline_padding )* ~ statement_separator ~ ( multiline_padding )* ~ layer_metadata_item )* ~
  singleline_padding* ~
  ( statement_separator ~ multiline_padding* )?

}
layer_metadata = {
  "(" ~ multiline_padding* ~ ( layer_metadata_item_sequence ~ multiline_padding* )? ~ ")"
}
layer_header =
{
  "#usda" ~ ( inline_padding )* ~ ( digit )+ ~ dot ~ ( digit )+ ~ ( dot ~ ( digit )+ )?
}

//
// root
//

layer_spec = {
  layer_header ~ multiline_padding* ~ ( layer_metadata ~ multiline_padding* )?
}
